title: Gaurav's Blogs
description: Sharing Generative AI Knowledge 
theme: jekyll-theme-cayman
collections:
  topics:
    output: true
    permalink: /:collection/:path/

# Exclude from processing
#exclude:
  # - .env
  #- venv/
